version: '3.8'
services:
  pulsar:
    image: apachepulsar/pulsar-all:2.7.0
    container_name: sx-pulsar
    ports: 
     - 6650:6650
     - 8080:8080
    command: ["bin/pulsar", "standalone"]
    networks: 
      - sx-net
networks:
  sx-net:
    external: true

