version: '3.8'
services:
  filebeat:
    container_name: sx_filebeat
    hostname: filebeat
    image: docker.elastic.co/beats/filebeat:7.10.0
    # Need to override user so we can access the log files, and docker.sock
    user: root
    volumes:
      - ./filebeat.yml:/usr/share/filebeat/filebeat.yml
      - /var/run/docker.sock:/var/run/docker.sock
      - {你的日志文件目录}:/var/log
    networks:
      - sx-net
      
networks:
  sx-net:
    external: true