version: "3.7"

services:
  config-srv:
    image: config-srv
    container_name: sx-config-srv
    restart: always
    environment:
      MICRO_REGISTRY: etcd
      MICRO_REGISTRY_ADDRESS: sx-etcd-node1:2379,sx-etcd-node2:2379,sx-etcd-node3:2379
      DATABASE_URL: root:mingchaonaxieshi@(sx-mysql:3306)/xconf?charset=utf8&parseTime=true&loc=Local
    networks:
      - sx-net
  admin-api:
    image: admin-api
    container_name: sx-admin-api
    restart: always
    environment:
      MICRO_REGISTRY: etcd
      MICRO_REGISTRY_ADDRESS: sx-etcd-node1:2379,sx-etcd-node2:2379,sx-etcd-node3:2379
    depends_on:
      - config-srv
    networks:
      - sx-net
  agent-api:
    image: agent-api
    container_name: sx-agent-api
    restart: always
    environment:
      MICRO_REGISTRY: etcd
      MICRO_REGISTRY_ADDRESS: sx-etcd-node1:2379,sx-etcd-node2:2379,sx-etcd-node3:2379
    depends_on:
      - config-srv
    networks:
      - sx-net
  micro:
    image: micro:latest
    container_name: sx-xconf-micro
    restart: always
    environment:
      MICRO_REGISTRY: etcd
      MICRO_REGISTRY_ADDRESS: sx-etcd-node1:2379,sx-etcd-node2:2379,sx-etcd-node3:2379
      CORS_ALLOWED_HEADERS: Content-Type,X-Token
      CORS_ALLOWED_ORIGINS: "*"
      CORS_ALLOWED_METHODS: OPTIONS,DELETE,GET,POST
      MICRO_API_ADDRESS: ":8090"
    expose:
      - 8090
    ports:
      - "8090:8090"
    command: ["--api_namespace=wm.sx.web", "api", "--handler=web"]
    networks:
      - sx-net
networks:
  sx-net:
    external: true # 使用自