version: "3.8"
services:
  clickhouse:
    container_name: sx-clickhouse
    image: yandex/clickhouse-server:20.8.7.15
    ports: 
      - 9000:9000
    volumes: 
      - ./etc:/etc/clickhouse-server
      - ./data:/var/lib/clickhouse/
    networks:
      - sx-net
networks:
  sx-net:
    external: true # 使用自定义创建好的网络，我创建的网络名加sx-net，方便与其他服务通信
