version: '3.8'
services: 
  kafka1: 
    image: wurstmeister/kafka
    container_name: sx-kafka1
    hostname: kafka1
    environment: 
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://:9092
      KAFKA_LISTENERS: PLAINTEXT://:9092
      KAFKA_BROKER_ID: 0
      KAFKA_ZOOKEEPER_CONNECT: zoo1:2181,zoo2:2181,zoo3:2181
    networks: 
      - sx-net
  kafka2: 
    image: wurstmeister/kafka
    container_name: sx-kafka2
    hostname: kafka2
    environment: 
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://:9092
      KAFKA_LISTENERS: PLAINTEXT://:9092
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zoo1:2181,zoo2:2181,zoo3:2181
    networks: 
      - sx-net
  kafka3: 
    image: wurstmeister/kafka
    container_name: sx-kafka3
    hostname: kafka3
    environment: 
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://:9092
      KAFKA_LISTENERS: PLAINTEXT://:9092
      KAFKA_BROKER_ID: 2
      KAFKA_ZOOKEEPER_CONNECT: zoo1:2181,zoo2:2181,zoo3:2181
    networks: 
      - sx-net
  kafka-manager:
    container_name: sx-kafka-manager
    image: sheepkiller/kafka-manager              ## 镜像：开源的web管理kafka集群的界面
    environment:
        ZK_HOSTS: zoo1:2181
    ports:
      - "9000:9000"                               
    networks: 
      - sx-net
networks:
  sx-net:
    external: true