version: '3.8'
services:
  zoo1:
    image: zookeeper:latest
    hostname: zoo1
    container_name: sx-zoo1
    environment:
      ZOO_MY_ID: 1
      ZOO_SERVERS: server.1=0.0.0.0:2888:3888;2181 server.2=zoo2:2888:3888;2181 server.3=zoo3:2888:3888;2181
    volumes: 
      - ./zoo1/data:/data
      - ./zoo1/datalog:/datalog
    networks: 
      - sx-net
  zoo2:
    image: zookeeper:latest
    hostname: zoo2
    container_name: sx-zoo2
    environment:
      ZOO_MY_ID: 2
      ZOO_SERVERS: server.1=zoo1:2888:3888;2181 server.2=0.0.0.0:2888:3888;2181 server.3=zoo3:2888:3888;2181
    volumes: 
      - ./zoo2/data:/data
      - ./zoo2/datalog:/datalog
    networks: 
      - sx-net
  zoo3:
    image: zookeeper:latest
    hostname: zoo3
    container_name: sx-zoo3
    environment:
      ZOO_MY_ID: 3
      ZOO_SERVERS: server.1=zoo1:2888:3888;2181 server.2=zoo2:2888:3888;2181 server.3=0.0.0.0:2888:3888;2181
    volumes: 
      - ./zoo3/data:/data
      - ./zoo3/datalog:/datalog
    networks: 
      - sx-net
  # pulsar-init:
  #   image: apachepulsar/pulsar:2.4.0
  #   container_name: sx-pulsar-init
  #   # command: ["ls", "-l"]
  #   command: ["bin/pulsar", "initialize-cluster-metadata", 
  #    "--cluster", "pulsar-log-msg-cluster",
  #    "--zookeeper", "sx-zoo1:2181", 
  #    "--configuration-store", "sx-zoo1:2181", 
  #    "--web-service-url", "http://sx-pulsar01:8080,sx-pulsar02:8080,sx-pulsar03:8080",
  #    "--web-service-url-tls", "https://sx-pulsar01:8443,sx-pulsar02:8443,sx-pulsar03:8443",
  #    "--broker-service-url", "pulsar://sx-pulsar01:6650,sx-pulsar02:6650,sx-pulsar03:6650",
  #    "--broker-service-url-tls", "pulsar+ssl://sx-pulsar01:6651,sx-pulsar02:6651,sx-pulsar03:6651"]
  #   networks: 
  #     - sx-net
  #   depends_on: 
  #     - zoo1
  #     - zoo2
  #     - zoo3
  bookie01:
    image: apachepulsar/pulsar:2.4.0
    container_name: sx-bookie01
    volumes: 
      - ./bookie/bookkeeper.conf:/pulsar/conf/bookkeeper.conf
      - ./bookie/data/bookie01:/pulsar/data
    command: ["bin/pulsar", "bookie"]
    networks: 
      sx-net: 
        ipv4_address: 172.18.10.1
    depends_on: 
        - zoo1
        - zoo2
        - zoo3
  bookie02:
    image: apachepulsar/pulsar:2.4.0
    container_name: sx-bookie02
    volumes: 
      - ./bookie/bookkeeper.conf:/pulsar/conf/bookkeeper.conf
      - ./bookie/data/bookie02:/pulsar/data
    command: ["bin/pulsar", "bookie"]
    networks: 
      sx-net: 
        ipv4_address: 172.18.10.2
    depends_on: 
      - zoo1
      - zoo2
      - zoo3
  broker01:
    image: apachepulsar/pulsar:2.4.0
    container_name: sx-broker01
    ports: 
      - 6650:6650
    volumes: 
      - ./broker/broker.conf:/pulsar/conf/broker.conf
    command: ["bin/pulsar", "broker"]
    networks: 
      - sx-net
    depends_on: 
      - zoo1
      - zoo2
      - zoo3
  broker02:
    image: apachepulsar/pulsar:2.4.0
    container_name: sx-broker02
    ports: 
      - 6651:6650
    volumes: 
      - ./broker/broker.conf:/pulsar/conf/broker.conf
    command: ["bin/pulsar", "broker"]
    networks: 
      - sx-net
    depends_on: 
      - zoo1
      - zoo2
      - zoo3
networks:
  sx-net:
    external: true
  

