version: '3.7'

services: 
  redis-manager:
    image: reasonduan/redis-manager:latest
    container_name: "sx-redis-manager"
    restart: always
    environment:
      DATASOURCE_DATABASE: redis_manager
      DATASOURCE_URL: jdbc:mysql://sx-mysql:3306/redis_manager?useUnicode=true&characterEncoding=utf-8&serverTimezone=GMT%2b8
      DATASOURCE_USERNAME: root
      DATASOURCE_PASSWORD: mingchaonaxieshi
    networks:
      - sx-net
networks:
  sx-net:
    external: true # 使用自定义创建好的网络，我创建的网络名加sx-net，方便与其他服务通信