version: '3.7'

services:
  drone-runner:
    container_name: sx-drone-runner
    image: drone/drone-runner-docker:latest
    restart: always
    environment:
      DRONE_RPC_PROTO: http
      DRONE_RPC_HOST: drone.wemeng.com
      DRONE_RPC_SECRET: ALQU2M0KdptXUdTPKcEw
      DRONE_RUNNER_CAPACITY: 2
      DRONE_RUNNER_NAME: ${HOSTNAME}
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /opt/store4/docker/drone-runner/data:/data
    networks:
      - sx-net
networks:
  sx-net:
    external: true