version: '3.8'

services:
  elasticsearch:
    container_name: sx-elasticsearch
    image: elasticsearch:7.10.1
    environment:
      discovery.type: "single-node"
      ES_JAVA_OPTS: "-Xms512m -Xmx512m"
    ports:
      - 9200:9200
      - 9300:9300
    volumes: 
      - ./es/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
      - ./es/data:/usr/share/elasticsearch/data
    networks:
      - sx-net
  kibana:
    container_name: sx-kibana
    image: kibana:7.10.1
    environment:
      discovery.type: "single-node"
    ports:
      - 5601:5601
    volumes: 
      - ./kibana/kibana.yml:/usr/share/kibana/config/kibana.yml
    networks:
      - sx-net
networks:
  sx-net:
    external: true # 使用自定义创建好的网络，我创建的网络名加sx-net，方便与其他服务通信